packages:
  base: !include
    file: common.yaml
    vars:
      reader_id: "1337-42-4711"
      reader_name: "thisismyreader"
      wims_url: http://10.10.37.213:5005
      display_platform: ssd1306_i2c
      display_model: "SSD1306 128x64"
      display_flip_x: true
      display_rotate: 0
      rtttl_pin: 10
      sda_pin: 4
      scl_pin: 5

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino
