---

# Unique ID for this reader
reader_id: "42"

# Wifi credentials
wifi_ssid: "It hurts when IP"
wifi_password: "swordfish"

# Password for fallback AP
fallback_psk: "t0ps3cr3t"

wims_url: "http://192.168.12.34
