apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
data:
  setup_db: |
    db.createCollection("items")
    db.items.createIndex( { "tag_uuid": 1 }, { unique: true } )
    db.createCollection("readers")
