# backend/configuration/config.yaml
schema_version: 1.0

database:
    host: "db"
    port: 27017
    name: "test"
    database: "test"
    user: "root"
    password: "example"

logging:
    level: "INFO"
