name: Playwright Tests
on:
  push:
    branches: [ main, dev ]
  # pull_request: # not working yet :(
  #   branches: [ main, dev ]
  # pull_request_target:
  #  branches: [ main, dev ]
  workflow_dispatch:


jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: print directory
      run: |
        pwd
        ls -la
        ls -la ./integration

    - name: Run Playwright Tests Container
      run: |
        docker compose -f ./docker-compose.yml -f ./integration/docker-compose.tests.yml up --build --abort-on-container-exit

    - name: Capture Docker Compose Logs
      if: always() # Ensure logs are captured regardless of success or failure
      run: |
        docker compose -f ./docker-compose.yml -f ./integration/docker-compose.tests.yml logs > ./integration/docker-compose-logs.txt || echo "Failed to capture logs."

    - uses: actions/upload-artifact@v4
      if:  always()
      with:
        name: docker-compose-logs
        path: ./integration/docker-compose-logs.txt

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ./integration/playwright-report/
        retention-days: 7

    - name: Cleanup Docker Compose
      if: always()
      run: |
        docker compose -f ./docker-compose.yml -f ./integration/docker-compose.tests.yml down
